name: Run Daily Forecast

on:
  schedule:
    - cron: '0 02 * * *'  # Jam 9.00 WIB
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch script
        run: python fetch_data.py  # Hanya simpan raw_data.csv

      - name: Run forecast script
        run: python forecast.py    # Baca raw_data.csv dan simpan hasil ke hasil_forecast.csv

      - name: Commit and Push CSV results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add *.csv || true
          git commit -m "Auto update CSV $(date +'%Y-%m-%d')" || echo "Nothing to commit"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
