name: Run Daily Forecast

on:
  schedule:
    - cron: '0 12 * * *'  # Jam 19.00 WIB
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # penting agar bisa reset

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch script
        run: python fetch_data.py

      - name: Run forecast script
        run: python forecast.py

      - name: Commit and Push CSV results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          # force sync to remote/main to avoid merge conflict
          git fetch origin
          git reset --hard origin/main

          # only add csv files
          git add *.csv || true
          git commit -m "Auto update CSV $(date +'%Y-%m-%d')" || echo "Nothing to commit"

          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
