name: Run Daily Forecast

on:
  schedule:
    - cron: '0 2 * * *'  # Waktu UTC, berarti jam 09.00 WIB setiap hari
  workflow_dispatch:     # Bisa juga dijalankan manual dari GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run forecast script
      run: python fetch_data.py

    - name: Commit CSV results
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add *.csv
        git commit -m "Auto update CSV $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
